### ISSUE TITLE
Small code refactor suggestion

### ISSUE THREAD

**Issue by apathy-dude** [clevett/Shadowrun-5e#2]
Not sure if this is the right place or if you would prefer a pull request or if you don't like my idea at all.  Any way:

The *Calculate ATTRIBUTES* section can be reduced into a single forEach loop with the help of template strings.  While unrolling the loop and template strings are slower it is for fields rarely updated and the speed difference is negligable while the code readability and ease of update has increased tremendously while also decreasing the chance of typos.  Taking a quick look this general idea could be applied in more places, especially if using objects instead of just strings.

Lines 3093 -> 3240 could be reduced to:
``` javascript
    [
        'body',
        'agility',
        'reaction',
        'strength',
        'willpower',
        'logic',
        'intuition',
        'charisma',
        'magic',
        'resonance',
    ].forEach(attr => {
        // Attach listener
        on(`change:${attr}_base change:${attr}_modifier change:${attr}_temp`, function() {
            // Load attribute values
            getAttrs([`${attr}_base`, `${attr}_modifier`, `${attr}_temp`], function(v) {
                // Do some math to calculate the total
                const bas = parseInt(v[`${attr}_base`]) || 0;
                const mod = parseInt(v[`${attr}_modifier`]) || 0;
                const tem = parseInt(v[`${attr}_temp`]) || 0;
                const bon = mod + tem;
                const stat = bas + bon;

                // Update the finalized total
                setAttrs({
                    [attr]: stat,
                    [`display_${attr}`]: bon === 0 ? bas : `${bas} (${stat})`
                });
            });
        });
    });
```

**Comment by clevett** [comment]
Hey thanks! Here is fine for these things. :) It let's me keep track of them. 

This is a big improvement to my current process. I'm going to do some refactoring this weekend and I'll throw this in for testing!  I'm a minimalist when it comes to code so I appreciate the suggestion to clean it up.

-Cassie

**Comment by clevett** [comment]
This code was exceptionally helpful! Thank you very much for offering it. :) I'm still a novice when it comes to Javascript. I applied this for the Matrix attributes & repeating_vehicles as well. Rolling out in pull request [4346](https://github.com/Roll20/roll20-character-sheets/pull/4346).
