### ISSUE TITLE
Unused soak code / ReferenceError

### ISSUE THREAD

**Issue by apathy-dude** [clevett/Shadowrun-5e#3]
Looking through some of the code when I come upon the update_soak function which has:

`var tot = rea + int + mod + tem;`

Those values aren't loaded and as far as I can tell nothing ever calls

`getAttrs(['soak'])`

**Comment by apathy-dude** [comment]
Also looks like the values set with the repeating_armor code is never used.

**Comment by clevett** [comment]
There is some unused code in there, I think. I was doing clever things with soak pools at one point and stopped due to feature creep. I'll go clean it up and make use removing Primary Armor clears the values.

No worries on all the updates. I appreciate the help.

**Comment by clevett** [comment]
Fixed the bad copy/paste code I had for soak. Rolling out in pull request [4346](https://github.com/Roll20/roll20-character-sheets/pull/4346).

I'll leave this ticket open as I think there may be other bugs still in my soak code related to _Primary Armor_.

**Comment by clevett** [comment]
This should be fixed now. The entire Primary Armor sheet worker got refactored and appears to be working correctly. Its some ugly code but its working for now.
