### ISSUE TITLE
Drones get 12 base condition monitor

### ISSUE THREAD

**Issue by apathy-dude** [clevett/Shadowrun-5e#5]
Currently all vehicles get `12 + body/2 + mod` while setting mod to -6 it's not exactly intuitive and there's plenty of screen realestate to add a is_drone checkbox and check for that inside of the update_physicalTrack function.

**Comment by clevett** [comment]
That would be a nice edition. I actually made the NPC sheets first, maybe a year ago, for my own campaigns. They need the most refactoring. I'll get a 'drone' option in there.

**Comment by clevett** [comment]
Completed. There is now a toggle in the settings for Vehicles. Rolling out in pull request [4346](https://github.com/Roll20/roll20-character-sheets/pull/4346).
